apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: istio-system
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~0
spec:
  releaseName: flagger
  chart:
    repository: https://flagger.app
    name: flagger
    version: 0.16.0
  values:
    slack:
      user: simple_jack
      channel: proj-cloud-tech
      url: https://hooks.slack.com/services/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
    metricsServer: http://prometheus.istio-system:9090
    image:
      repository: weaveworks/flagger
      tag: 0.16.0
      pullPolicy: IfNotPresent
